"""add_cost_basis_status_to_positions

Revision ID: 334aec2ec9cf
Revises: 0002_add_portfolio_snapshots
Create Date: 2026-07-14 23:32:55.106926

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "334aec2ec9cf"
down_revision: str | None = "0002_add_portfolio_snapshots"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions",
        sa.Column(
            "cost_basis_status",
            sa.String(length=32),
            server_default=sa.text("'unavailable'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "cost_basis_status")
    # ### end Alembic commands ###
